header_pages:
  - index.md
  - about.md
  - blog.md

footer: '<a href="https://twitter.com/teresinahc">twitter</a> | <a href="https://github.com/teresinahc">github</a>'

#style: light # dark (default) or light

theme: jekyll-theme-console

plugins:
  - jekyll-seo-tag
